import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { AuthProvider } from "@/context/AuthContext";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <AuthProvider>

        
        <Providers>
          {/* Move all client components inside Providers */}
          <div className="flex grainy-dark flex-col min-h-screen">
            {children}
          </div>
        </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}